"""add processing_status to resume

Revision ID: 5568e31ba5da
Revises: e85c6b417414
Create Date: 2026-09-19 16:00:36.511778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5568e31ba5da'
down_revision: Union[str, Sequence[str], None] = 'e85c6b417414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('processing_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'processing_status')
    # ### end Alembic commands ###
