"""add linkedin_url to candidate profile

Revision ID: e85c6b417414
Revises: ca9995cacc43
Create Date: 2026-09-19 15:35:08.298567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85c6b417414'
down_revision: Union[str, Sequence[str], None] = 'ca9995cacc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'linkedin_url')
    # ### end Alembic commands ###
